fix problem with Mono 4.6 related to Jayrock.Json
the error message was:
[00:15:48] /root/lbs-openpetra/openpetra-test-server-sqlite/openpetra-test/csharp/ICT/Testing/lib/Common/IO/test.cs(423,13) : error CS0012: The type `System.Dynamic.IDynamicMetaObjectProvider' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'